sonar.organization=jcoorp
sonar.projectKey=JCoorp_SnackUP-core
sonar.projectName=SnackUP
sonar.sourceEncoding=UTF-8
sonar.sources=lib
sonar.tests=test
sonar.dart.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,lib/firebase_options.dart
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
