import fs from "node:fs";
import path from "node:path";
import http from "node:http";
import crypto from "node:crypto";
import { URL } from "node:url";

// -------- env / local state --------
function loadEnv(file = path.resolve(process.cwd(), ".env")) {
  if (!fs.existsSync(file)) return;
  for (const raw of fs.readFileSync(file, "utf8").split(/\r?\n/)) {
    const line = raw.trim(); if (!line || line.startsWith("#")) continue;
    const i = line.indexOf("="); if (i < 1) continue;
    const key = line.slice(0, i).trim(); let value = line.slice(i + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) value = value.slice(1, -1);
    if (!(key in process.env)) process.env[key] = value;
  }
}
function need(...names) { const m = names.filter((n) => !process.env[n]); if (m.length) throw new Error(`Faltan variables: ${m.join(", ")}`); }
function nenv(name, fallback) { const n = Number.parseInt(process.env[name] || "", 10); return Number.isFinite(n) ? n : fallback; }
loadEnv();
const dataDir = path.resolve(".data"); fs.mkdirSync(dataDir, { recursive: true });
const tokenFile = path.join(dataDir, "canva-tokens.json");
const oauthFile = path.join(dataDir, "oauth-state.json");
function writeJson(file, value) { const tmp = `${file}.tmp`; fs.writeFileSync(tmp, JSON.stringify(value, null, 2), { mode: 0o600 }); fs.renameSync(tmp, file); }
function readJson(file) { return fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, "utf8")) : null; }

// -------- Canva REST / OAuth --------
const CANVA = "https://api.canva.com/rest/v1";
function basicAuth() { need("CANVA_CLIENT_ID", "CANVA_CLIENT_SECRET"); return `Basic ${Buffer.from(`${process.env.CANVA_CLIENT_ID}:${process.env.CANVA_CLIENT_SECRET}`).toString("base64")}`; }
async function body(res) { const text = await res.text(); let j; try { j = text ? JSON.parse(text) : {}; } catch { j = { raw: text }; } if (!res.ok) { const e = new Error(j?.message || j?.error_description || `${res.status} ${res.statusText}`); e.body = j; throw e; } return j; }
function saveTokens(t) { writeJson(tokenFile, { ...t, obtained_at: Date.now(), expires_at: t.expires_in ? Date.now() + Number(t.expires_in) * 1000 : undefined }); }
async function tokenRequest(params) { const res = await fetch(`${CANVA}/oauth/token`, { method: "POST", headers: { Authorization: basicAuth(), "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams(params) }); const t = await body(res); saveTokens(t); return t; }
async function accessToken() { const t = readJson(tokenFile); if (!t) throw new Error("Canva no está autorizado. Ejecuta: npm run oauth"); if (t.access_token && t.expires_at && Date.now() < t.expires_at - 300000) return t.access_token; if (!t.refresh_token) throw new Error("No hay refresh token. Reautoriza Canva."); return (await tokenRequest({ grant_type: "refresh_token", refresh_token: t.refresh_token })).access_token; }
async function canva(pathname, options = {}) { const res = await fetch(`${CANVA}${pathname}`, { ...options, headers: { Authorization: `Bearer ${await accessToken()}`, ...(options.headers || {}) } }); return body(res); }
async function listDesigns(params = {}) { const q = new URLSearchParams({ limit: String(params.limit || 25), ownership: params.ownership || "any", sort_by: params.sort_by || "modified_descending" }); if (params.query) q.set("query", params.query); return canva(`/designs?${q}`); }
async function getDesign(id) { return canva(`/designs/${encodeURIComponent(id)}`); }
async function createPresentation(title) { return canva("/designs", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ type: "type_and_asset", design_type: { type: "preset", name: "presentation" }, title }) }); }
async function importFile(file, title) { const abs = path.resolve(file); const bytes = fs.readFileSync(abs); const ext = path.extname(abs).toLowerCase(); const mime = { ".pptx":"application/vnd.openxmlformats-officedocument.presentationml.presentation", ".ppt":"application/vnd.ms-powerpoint", ".pdf":"application/pdf", ".docx":"application/vnd.openxmlformats-officedocument.wordprocessingml.document", ".xlsx":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" }[ext]; if (!mime) throw new Error(`Formato no soportado: ${ext}`); return canva("/imports", { method: "POST", headers: { "Content-Type":"application/octet-stream", "Content-Length": String(bytes.length), "Import-Metadata": JSON.stringify({ title_base64: Buffer.from(title,"utf8").toString("base64"), mime_type: mime }) }, body: bytes }); }
async function importUrl(url, title, mime) { return canva("/url-imports", { method: "POST", headers: { "Content-Type":"application/json" }, body: JSON.stringify({ title, url, ...(mime ? { mime_type:mime } : {}) }) }); }
async function waitJob(pathPrefix, id, timeout = 180000) { const end = Date.now() + timeout; while (Date.now() < end) { const r = await canva(`/${pathPrefix}/${encodeURIComponent(id)}`); if (r.job?.status === "success") return r; if (r.job?.status === "failed") throw new Error(`Trabajo Canva falló: ${JSON.stringify(r.job.error || r.job)}`); await new Promise((r) => setTimeout(r, 1500)); } throw new Error(`Timeout Canva job ${id}`); }
async function exportDesign(id, type = "pptx") { const fmt = { type }; if (type === "jpg") fmt.quality = 90; const s = await canva("/exports", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({ design_id:id, format:fmt }) }); return s.job?.id ? waitJob("exports", s.job.id) : s; }
async function downloadUrls(urls, name = "canva-export") { const out = path.resolve(process.env.CANVA_OUTBOX || "./outbox"); fs.mkdirSync(out,{recursive:true}); const files=[]; for (let i=0;i<urls.length;i++){ const res=await fetch(urls[i]); if(!res.ok) throw new Error(`Download ${res.status}`); const ct=res.headers.get("content-type")||""; const ext=ct.includes("pdf")?".pdf":ct.includes("presentation")?".pptx":ct.includes("png")?".png":ct.includes("jpeg")?".jpg":ct.includes("gif")?".gif":ct.includes("mp4")?".mp4":".bin"; const f=path.join(out,`${name}${urls.length>1?`-${i+1}`:""}${ext}`); fs.writeFileSync(f,Buffer.from(await res.arrayBuffer())); files.push(f);} return files; }

// -------- OAuth local server --------
function b64url(b) { return b.toString("base64").replace(/=/g,"").replace(/\+/g,"-").replace(/\//g,"_"); }
function rand(n=48) { return b64url(crypto.randomBytes(n)); }
function authTarget() { need("CANVA_CLIENT_ID","CANVA_CLIENT_SECRET","CANVA_REDIRECT_URI"); const verifier=rand(64).slice(0,96); const challenge=b64url(crypto.createHash("sha256").update(verifier).digest()); const state=rand(32); writeJson(oauthFile,{verifier,state,created_at:Date.now()}); const u=new URL("https://www.canva.com/api/oauth/authorize"); u.searchParams.set("code_challenge",challenge); u.searchParams.set("code_challenge_method","S256"); u.searchParams.set("scope",process.env.CANVA_SCOPES||"design:meta:read design:content:read design:content:write"); u.searchParams.set("response_type","code"); u.searchParams.set("client_id",process.env.CANVA_CLIENT_ID); u.searchParams.set("state",state); u.searchParams.set("redirect_uri",process.env.CANVA_REDIRECT_URI); return u.toString(); }
function page(res,status,html){res.writeHead(status,{"Content-Type":"text/html; charset=utf-8","Cache-Control":"no-store"});res.end(`<!doctype html><html><body style="font-family:system-ui;max-width:760px;margin:50px auto;padding:20px">${html}</body></html>`);}
async function runOAuth(){ const port=nenv("CANVA_OAUTH_PORT",8787); const server=http.createServer(async(req,res)=>{ try{ const u=new URL(req.url||"/",`http://127.0.0.1:${port}`); if(u.pathname==="/"||u.pathname==="/auth/start"){const t=authTarget(); if(u.pathname==="/auth/start"){res.writeHead(302,{Location:t});return res.end();} return page(res,200,'<h1>SnackUp Canva Bridge</h1><a href="/auth/start">Autorizar Canva</a>');} if(u.pathname==="/oauth/callback"){const code=u.searchParams.get("code"),state=u.searchParams.get("state"),s=readJson(oauthFile); if(!code||!state||!s||state!==s.state||Date.now()-s.created_at>600000) return page(res,400,"<h1>OAuth inválido o expirado</h1>"); await tokenRequest({grant_type:"authorization_code",code_verifier:s.verifier,code,redirect_uri:process.env.CANVA_REDIRECT_URI}); fs.rmSync(oauthFile,{force:true}); return page(res,200,"<h1>Canva conectado ✓</h1><p>Los tokens quedaron solo en tu computadora. Puedes cerrar esta pestaña.</p>");} return page(res,404,"<h1>No encontrado</h1>"); }catch(e){console.error(e);return page(res,500,`<h1>Error</h1><pre>${String(e.message||e)}</pre>`);} }); server.listen(port,"127.0.0.1",()=>console.log(`Abre http://127.0.0.1:${port}/auth/start`)); }

// -------- GitHub job queue --------
function ghCfg(){need("GITHUB_TOKEN","GITHUB_OWNER","GITHUB_REPO","GITHUB_REF");return{token:process.env.GITHUB_TOKEN,owner:process.env.GITHUB_OWNER,repo:process.env.GITHUB_REPO,ref:process.env.GITHUB_REF,jobs:process.env.GITHUB_JOBS_PATH||"tools/canva-bridge/jobs",results:process.env.GITHUB_RESULTS_PATH||"tools/canva-bridge/results"};}
async function gh(pathname,opt={}){const c=ghCfg();const res=await fetch(`https://api.github.com${pathname}`,{...opt,headers:{Accept:"application/vnd.github+json",Authorization:`Bearer ${c.token}`,"X-GitHub-Api-Version":"2022-11-28","User-Agent":"snackup-canva-bridge",...(opt.headers||{})}});const t=await res.text();let j;try{j=t?JSON.parse(t):{};}catch{j={raw:t};}if(!res.ok){const e=new Error(`GitHub ${res.status}: ${j.message||t}`);e.status=res.status;throw e;}return j;}
async function jobs(){const c=ghCfg();const a=await gh(`/repos/${c.owner}/${c.repo}/contents/${c.jobs}?ref=${encodeURIComponent(c.ref)}`);return Array.isArray(a)?a.filter(x=>x.type==="file"&&x.name.endsWith(".json")&&!x.name.startsWith("README")):[];}
async function readJob(apiUrl){const item=await gh(new URL(apiUrl).pathname);return{json:JSON.parse(Buffer.from((item.content||"").replace(/\n/g,""),"base64").toString("utf8")),sha:item.sha};}
async function result(id,payload){const c=ghCfg(),p=`${c.results}/${id}.json`,content=Buffer.from(JSON.stringify(payload,null,2)).toString("base64");let sha;try{sha=(await gh(`/repos/${c.owner}/${c.repo}/contents/${p}?ref=${encodeURIComponent(c.ref)}`)).sha;}catch(e){if(e.status!==404)throw e;}return gh(`/repos/${c.owner}/${c.repo}/contents/${p}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:`canva-bridge: result ${id}`,content,branch:c.ref,...(sha?{sha}:{})})});}
async function execute(j){switch(j.action){case"list_designs":return listDesigns(j.params||{});case"get_design":return getDesign(j.params.design_id);case"create_presentation":return createPresentation(j.params.title||"Nueva presentación");case"import_local_file":{const inbox=path.resolve(process.env.CANVA_INBOX||"./inbox"),file=path.join(inbox,path.basename(j.params.filename));if(!fs.existsSync(file))throw new Error(`Falta ${file}`);const s=await importFile(file,j.params.title||path.parse(file).name);return s.job?.id?waitJob("imports",s.job.id):s;}case"import_url":{const s=await importUrl(j.params.url,j.params.title,j.params.mime_type);return s.job?.id?waitJob("url-imports",s.job.id):s;}case"export_design":{const r=await exportDesign(j.params.design_id,j.params.type||"pptx");const files=r.job?.urls?.length?await downloadUrls(r.job.urls,j.params.filename||`canva-${j.params.design_id}`):[];return{...r,local_files:files};}default:throw new Error(`Acción no soportada: ${j.action}`);}}
async function runDaemon(){const poll=nenv("POLL_SECONDS",30)*1000,processedFile=path.join(dataDir,"processed-jobs.json");fs.mkdirSync(path.resolve(process.env.CANVA_INBOX||"./inbox"),{recursive:true});fs.mkdirSync(path.resolve(process.env.CANVA_OUTBOX||"./outbox"),{recursive:true});console.log(`Daemon Canva Bridge activo. Poll cada ${poll/1000}s`);while(true){try{const processed=readJson(processedFile)||{};for(const f of await jobs()){const {json:j,sha}=await readJob(f.url),id=j.id||path.basename(f.name,".json");if(processed[id]===sha)continue;const started=new Date().toISOString();try{const data=await execute(j);await result(id,{id,ok:true,action:j.action,started_at:started,finished_at:new Date().toISOString(),data});}catch(e){await result(id,{id,ok:false,action:j.action,started_at:started,finished_at:new Date().toISOString(),error:String(e.message||e),details:e.body});}processed[id]=sha;writeJson(processedFile,processed);}}catch(e){console.error(e);}await new Promise(r=>setTimeout(r,poll));}}

// -------- CLI --------
async function runCli(args){const [cmd,...a]=args;const print=x=>console.log(JSON.stringify(x,null,2));if(cmd==="list")return print(await listDesigns({query:a.join(" ")||undefined}));if(cmd==="get")return print(await getDesign(a[0]));if(cmd==="create-presentation")return print(await createPresentation(a.join(" ")||"Nueva presentación"));if(cmd==="import"){const s=await importFile(a[0],a.slice(1).join(" ")||path.parse(a[0]).name);return print(s.job?.id?await waitJob("imports",s.job.id):s);}if(cmd==="import-url"){const s=await importUrl(a[0],a[1]||"Importado por Canva Bridge",a[2]);return print(s.job?.id?await waitJob("url-imports",s.job.id):s);}if(cmd==="export"){const r=await exportDesign(a[0],a[1]||"pptx");const files=r.job?.urls?.length?await downloadUrls(r.job.urls,a[2]||`canva-${a[0]}`):[];return print({...r,local_files:files});}console.log('Uso: npm run cli -- list [texto] | get ID | create-presentation "Título" | import archivo.pptx "Título" | import-url URL "Título" [MIME] | export ID [pptx|pdf|png|jpg|gif|mp4] [nombre]');}

const [mode,...args]=process.argv.slice(2);
try{if(mode==="oauth")await runOAuth();else if(mode==="daemon")await runDaemon();else if(mode==="cli")await runCli(args);else console.log("Usa: npm run oauth | npm run daemon | npm run cli -- ...");}catch(e){console.error(e?.stack||e);process.exitCode=1;}
