// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK5N-TA3bA7VKv5TJQqUXICA617wOywzU',
    appId: '1:685155856831:web:8047d0df9ed1522ff5b10a',
    messagingSenderId: '685155856831',
    projectId: 'snackup-8fe96',
    authDomain: 'snackup-8fe96.firebaseapp.com',
    storageBucket: 'snackup-8fe96.firebasestorage.app',
    measurementId: 'G-PE33SNB39W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdNKrdRBFXOW0rOei9AddO7joTayLRB8o',
    appId: '1:685155856831:android:2df64bce8711eb6ef5b10a',
    messagingSenderId: '685155856831',
    projectId: 'snackup-8fe96',
    storageBucket: 'snackup-8fe96.firebasestorage.app',
  );
}
